/**
 * Sample merged data for testing/demo
 * frontend/src/lib/mock-data/merged-data-sample.ts
 */

import type { MergedData } from '@/types/merged-data'

export const SAMPLE_MERGED_DATA: MergedData = {
  insured: {
    businessName: 'ABC Manufacturing Corp',
    dba: 'ABC Mfg',
    entityType: 'Corporation',
    federalId: '12-3456789',
    stateId: 'TX-9876543',
    website: 'www.abcmfg.com',
    yearEstablished: 1995,
    businessDescription: 'Manufacturing and distribution of industrial equipment and components',
    mailingAddress: {
      street: '123 Industrial Parkway',
      street2: 'Suite 200',
      city: 'Houston',
      state: 'TX',
      zip: '77001',
      county: 'Harris',
      country: 'USA',
    },
    primaryContact: {
      name: 'John Smith',
      title: 'Risk Manager',
      phone: '713-555-0100',
      phoneExt: '101',
      email: 'jsmith@abcmfg.com',
      fax: '713-555-0199',
    },
  },

  locations: [
    {
      id: 'loc-001',
      locationNumber: 1,
      address: {
        street: '123 Industrial Parkway',
        city: 'Houston',
        state: 'TX',
        zip: '77001',
        county: 'Harris',
      },
      buildingValue: 2500000,
      contentValue: 1800000,
      businessIncomeValue: 500000,
      occupancy: 'Manufacturing',
      constructionType: 'Masonry Non-Combustible',
      protectionClass: '3',
      yearBuilt: 1998,
      squareFootage: 45000,
      numberOfStories: 2,
      sprinklered: true,
      buildingDetails: {
        roofType: 'Built-up',
        roofYear: 2015,
        hvacYear: 2018,
        plumbingYear: 2010,
        electricalYear: 2012,
        foundationType: 'Slab',
        exteriorWalls: 'Concrete Block',
      },
    },
    {
      id: 'loc-002',
      locationNumber: 2,
      address: {
        street: '456 Warehouse Drive',
        city: 'Dallas',
        state: 'TX',
        zip: '75201',
        county: 'Dallas',
      },
      buildingValue: 1500000,
      contentValue: 950000,
      businessIncomeValue: 300000,
      occupancy: 'Warehouse/Distribution',
      constructionType: 'Steel Frame',
      protectionClass: '4',
      yearBuilt: 2005,
      squareFootage: 32000,
      numberOfStories: 1,
      sprinklered: true,
      buildingDetails: {
        roofType: 'Metal',
        roofYear: 2005,
        hvacYear: 2015,
        foundationType: 'Slab',
        exteriorWalls: 'Metal Panels',
      },
    },
  ],

  exposures: {
    annualRevenue: 12500000,
    annualPayroll: 3200000,
    numberOfEmployees: 85,
    fullTimeEmployees: 72,
    partTimeEmployees: 8,
    seasonalEmployees: 5,
    revenueByClassCode: [
      {
        classCode: '91343',
        classDescription: 'Machinery or Equipment Mfg',
        revenue: 8500000,
        percentage: 68,
      },
      {
        classCode: '47213',
        classDescription: 'Warehousing',
        revenue: 4000000,
        percentage: 32,
      },
    ],
    payrollByClassCode: [
      {
        classCode: '91343',
        classDescription: 'Machinery or Equipment Mfg',
        payroll: 2200000,
        numberOfEmployees: 55,
      },
      {
        classCode: '47213',
        classDescription: 'Warehousing',
        payroll: 1000000,
        numberOfEmployees: 30,
      },
    ],
  },

  lossHistory: {
    yearsOfHistory: 5,
    losses: [
      {
        id: 'loss-001',
        date: '2023-03-15',
        lossType: 'Property Damage',
        description: 'Water damage from sprinkler malfunction in warehouse',
        claimStatus: 'Closed',
        paidAmount: 45000,
        reserveAmount: 0,
        totalIncurred: 45000,
        claimNumber: 'CL-2023-1501',
        locationId: 'loc-002',
      },
      {
        id: 'loss-002',
        date: '2022-11-08',
        lossType: 'General Liability',
        description: 'Slip and fall in parking lot',
        claimStatus: 'Closed',
        paidAmount: 12500,
        reserveAmount: 0,
        totalIncurred: 12500,
        claimNumber: 'CL-2022-1108',
        locationId: 'loc-001',
      },
      {
        id: 'loss-003',
        date: '2021-06-22',
        lossType: 'Property Damage',
        description: 'Wind damage to roof',
        claimStatus: 'Closed',
        paidAmount: 28000,
        reserveAmount: 0,
        totalIncurred: 28000,
        claimNumber: 'CL-2021-0622',
        locationId: 'loc-001',
      },
      {
        id: 'loss-004',
        date: '2024-02-10',
        lossType: 'Products Liability',
        description: 'Product defect claim',
        claimStatus: 'Open',
        paidAmount: 15000,
        reserveAmount: 50000,
        totalIncurred: 65000,
        claimNumber: 'CL-2024-0210',
      },
    ],
    summary: {
      totalClaims: 4,
      totalPaid: 100500,
      totalIncurred: 150500,
      claimsByYear: {
        '2024': 1,
        '2023': 1,
        '2022': 1,
        '2021': 1,
      },
      claimsByType: {
        'Property Damage': 2,
        'General Liability': 1,
        'Products Liability': 1,
      },
      averageClaimSize: 37625,
    },
  },

  coverage: {
    currentCarrier: 'ABC Insurance Company',
    policyNumber: 'CP-2024-123456',
    effectiveDate: '2024-01-01',
    expirationDate: '2025-01-01',
    limits: {
      generalLiability: {
        aggregateLimit: 2000000,
        perOccurrenceLimit: 1000000,
        productsCompletedOps: 2000000,
        personalAdvertisingInjury: 1000000,
        medicalExpense: 10000,
      },
      property: {
        building: 4000000,
        businessPersonalProperty: 2750000,
        businessIncome: 800000,
        extraExpense: 200000,
      },
      crime: {
        employeeTheft: 100000,
        forgeryAlteration: 50000,
      },
      umbrella: {
        limit: 5000000,
      },
    },
    deductibles: {
      property: 5000,
      windHail: 25000,
      earthquake: 50000,
      flood: 10000,
      crime: 2500,
    },
    additionalCoverages: [
      {
        name: 'Equipment Breakdown',
        limit: 1000000,
        premium: 2500,
        included: true,
      },
      {
        name: 'Cyber Liability',
        limit: 500000,
        premium: 3500,
        included: true,
      },
      {
        name: 'Employment Practices Liability',
        limit: 1000000,
        premium: 4200,
        included: false,
      },
    ],
  },

  metadata: {
    mergedAt: new Date().toISOString(),
    sourceFileCount: 4,
    sourceFiles: [
      'ACORD_126_filled.pdf',
      'Loss_Run_2019-2024.pdf',
      'Schedule_of_Values.xlsx',
      'Supplemental_Application.pdf',
    ],
    confidence: 87,
    completeness: 92,
    warnings: [
      'Missing roof maintenance records for Location 2',
      'Employment Practices Liability coverage declined - verify with client',
      'One open claim requires reserve review',
    ],
    dataQuality: {
      insured: {
        score: 95,
        fieldsPopulated: 10,
        fieldsTotal: 11,
        missingCriticalFields: ['stateId'],
      },
      locations: {
        score: 90,
        fieldsPopulated: 18,
        fieldsTotal: 20,
        missingCriticalFields: [],
      },
      exposures: {
        score: 88,
        fieldsPopulated: 7,
        fieldsTotal: 8,
        missingCriticalFields: [],
      },
      lossHistory: {
        score: 92,
        fieldsPopulated: 11,
        fieldsTotal: 12,
        missingCriticalFields: [],
      },
      coverage: {
        score: 94,
        fieldsPopulated: 15,
        fieldsTotal: 16,
        missingCriticalFields: [],
      },
    },
  },
}